config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'events#index'
  resources :events, only: [:index]
  resources :new_events, only: [:index]
  resources :topics, only: :show do
    resources :posts, only: [:create]
  end
  resources :new_event_marks, only: [:update]
  resources :users, only: :create

  resources :city_search_results, only: [:index]
  resources :tag_search_results, only: [:index]

  resources :filters, only: [:destroy]
  resources :filtered_events_lists, only: [:create, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  include IdentifiedSearch

  has_many :places

  validates :name, presence: true, uniqueness: true

  def id_string
    name
  end
end

app/models/event.rb
class Event < ApplicationRecord
  include IdentifiedSearch

  belongs_to :place
  has_and_belongs_to_many :tags, join_table: 'events_tags'
  has_many :topics

  delegate :city, :city_id, to: :place, allow_nil: true

  validates :title, presence: true
  validates :description, presence: true
  validates :begin_time, presence: true
  validates :end_time, presence: true
  validates :place_id, presence: true

  after_create :broadcast_notification

  def tag_names
    tags.pluck(:name)
  end

  def tag_names=(tags_list)
    tags_list = tags_list.map(&:presence).compact.map(&:downcase)

    found_tags = Tag.where(name: tags_list).to_a
    found_tag_names = found_tags.map(&:name)

    not_found_tag_names = tags_list - found_tag_names
    new_tags = not_found_tag_names.map{ |tag_name| Tag.new(name: tag_name) }

    self.tags = found_tags + new_tags
  end

  def id_string
    "#{city.name} / #{place.title} / #{title}"
  end

  private

  def broadcast_notification
    return if begin_time < Time.now

    NewEventNotificationJob.perform_later(self)
  end
end

app/models/events_lister.rb
class EventsLister
  attr_reader :filter

  def initialize(filter_params)
    @filter = Filter.new(filter_params)
  end

  def events
    @events ||= events_filter_applier.apply_filter
  end

  private

  def events_filter_applier
    @filter_applier ||= EventsFilterApplier.new(filter)
  end
end

app/models/filter.rb
class Filter < ApplicationRecord
  belongs_to :user

  belongs_to :city, optional: true
  belongs_to :tag, optional: true

  validates :user_id, presence: true
  validates :name, presence: true

  scope :suitable_by_city, ->(city_id) { where(arel_table[:city_id].eq(city_id).or(arel_table[:city_id].eq(nil)))  }
  scope :suitable_by_tag_ids, ->(tag_ids) { where(arel_table[:tag_id].in(tag_ids).or(arel_table[:tag_id].eq(nil)))  }

  scope :suitable_by_time, ->(event_beginning_time) {
    where(arel_table[:begin_interval].lt(event_beginning_time))
      .or(where(arel_table[:end_interval].gt(event_beginning_time)))
      .or(where(begin_interval: nil, end_interval: nil))
  }
end

app/models/filter_builder.rb
class FilterBuilder
  attr_reader :user, :filter_params

  def self.build_filter(user, filter_params)
    instance = new(user, filter_params)
    instance.build
  end

  def initialize(user, filter_params)
    @user = user
    @filter_params = filter_params
  end

  def build
    user.filters.build(normalized_params)
  end

  def normalized_params
    result = filter_params.select{ |k, v| v.present? }
    result[:name] ||= "Filter##{Time.now.to_f}"
    result
  end
end

app/models/place.rb
class Place < ApplicationRecord
  include IdentifiedSearch

  has_many :events
  belongs_to :city

  validates :city_id, presence: true
  validates :title, presence: true
  validates :description, presence: true

  def id_string
    "#{city.name} / #{title}"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_one :event, through: :topic

  validates :message, presence: true
  validates :user_id, presence: true
  validates :topic_id, presence: true
end

app/models/post_creator.rb
class PostCreator
  attr_reader :user, :topic_id, :topic

  def initialize(user, topic_id)
    @user = user
    @topic_id = topic_id
    @topic = Topic.find(topic_id)
  end

  def create!(params)
    topic.posts.create!(params.merge(user_id: user.id))
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles


  belongs_to :resource,
             :polymorphic => true,
             :optional => true


  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tag.rb
class Tag < ApplicationRecord
  include IdentifiedSearch

  has_and_belongs_to_many :events, join_table: 'events_tags'

  validates :name, presence: true

  def id_string
    name
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :event
  has_many :posts

  validates :title, presence: true
  validates :description, presence: true
  validates :event_id, presence: true

  delegate :title, to: :event, prefix: true
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :validatable#, :confirmable

  has_many :filters
  has_many :posts

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    lister = EventsLister.new(permitted_filter_params)
    @events = lister.events.eager_load(:topics).page(params[:page])
    @filter = lister.filter
  end

  private

  def permitted_filter_params
    params.fetch(:filter, {}).permit(:city_id, :tag_id, :begin_interval, :end_interval)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def search
    result = Tag.identified_search(params[:query], :name)
    render json: result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.slim
.event
  .event-title
    = event.title
  .times
    small.begin-time-title Начинается:
    small.begin-time-value= I18n.l event.begin_time, format: :long
    small.separator |
    small.end-time-title Заканчивается:
    small.end-time-value= I18n.l event.end_time, format: :long
  - if event.tags.any?
    .tags
      span Тематика:
      '
      span= event.tag_names.join(', ')
  .event-description
    = event.description

  .topics
    = render event.topics

app/views/events/_filter.html.slim
.filters-block
  .filter-block
    strong Фильтр
    = semantic_form_for @filter, url: filtered_events_lists_path do |f|
      = f.inputs do
        = f.input :city,
                  label: false,
                  as: :select,
                  collection: f.object.city&.for_identified_select || [],
                  selected: f.object.city_id,
                  input_html: { class: 'select2-remote',
                                data: { placeholder: 'City',
                                        source: city_search_results_path,
                                        allow_clear: true,
                                        ajax__delay: 500 } }
        = f.input :begin_interval,
                  as: :string,
                  label: false,
                  input_html: { class: 'date-time-picker', placehoder: 'Begin interval' }
        = f.input :end_interval,
                  as: :string,
                  label: false,
                  input_html: { class: 'date-time-picker', placehoder: 'End interval' }
        = f.input :tag_id,
                  label: false,
                  as: :select,
                  collection: f.object.tag&.for_identified_select || [],
                  selected: f.object.tag_id,
                  input_html: { class: 'select2-remote',
                                data: { placeholder: 'Tag',
                                        source: tag_search_results_path,
                                        allow_clear: true,
                                        ajax__delay: 500 } }
        - if user_signed_in?
          = f.input :save, as: :boolean, input_html: { name: 'save' }
          = f.input :name, a: :string, label: false, input_html: { placehoder: 'filter name' }
        = f.submit 'filter'
        = link_to 'clear', events_path

  - if user_signed_in?
    .saved-filters
      strong Сохранённые фильтры
      .filters-list
        = select_tag(:filters,  options_for_select([['Select filter', '']] + current_user.filters.pluck(:name, :id)))
      .buttons
        = semantic_form_for :filter, url: '', html: { id: 'apply_filter' }, method: :patch do |f|
          = f.submit 'filter events'

        = semantic_form_for :filter, url: '', html: { id: 'delete_filter' }, method: :delete do |f|
          = f.submit 'remove filter'

app/views/events/index.html.slim
.content-block
  h1
    | События

  .events
    = render @events

  = paginate @events

= render partial: 'filter'