config/routes.rb
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'events#index'
  resources :events, only: [:index]
  resources :new_events, only: [:index]
  resources :topics, only: :show do
    resources :posts, only: [:create]
  end
  resources :new_event_marks, only: [:update]
  resources :users, only: :create

  resources :city_search_results, only: [:index]
  resources :tag_search_results, only: [:index]

  resources :filters, only: [:destroy]
  resources :filtered_events_lists, only: [:create, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  include IdentifiedSearch

  has_many :places

  validates :name, presence: true, uniqueness: true

  def id_string
    name
  end
end

app/models/event.rb
class Event < ApplicationRecord
  include IdentifiedSearch

  belongs_to :place
  has_and_belongs_to_many :tags, join_table: 'events_tags'
  has_many :topics

  delegate :city, :city_id, to: :place, allow_nil: true

  validates :title, presence: true
  validates :description, presence: true
  validates :begin_time, presence: true
  validates :end_time, presence: true
  validates :place_id, presence: true

  after_create :broadcast_notification

  def tag_names
    tags.pluck(:name)
  end

  def tag_names=(tags_list)
    tags_list = tags_list.map(&:presence).compact.map(&:downcase)

    found_tags = Tag.where(name: tags_list).to_a
    found_tag_names = found_tags.map(&:name)

    not_found_tag_names = tags_list - found_tag_names
    new_tags = not_found_tag_names.map{ |tag_name| Tag.new(name: tag_name) }

    self.tags = found_tags + new_tags
  end

  def id_string
    "#{city.name} / #{place.title} / #{title}"
  end

  private

  def broadcast_notification
    return if begin_time < Time.now

    NewEventNotificationJob.perform_later(self)
  end
end

app/models/events_lister.rb
class EventsLister
  attr_reader :filter

  def initialize(filter_params)
    @filter = Filter.new(filter_params)
  end

  def events
    @events ||= events_filter_applier.apply_filter
  end

  private

  def events_filter_applier
    @filter_applier ||= EventsFilterApplier.new(filter)
  end
end

app/models/filter.rb
class Filter < ApplicationRecord
  belongs_to :user

  belongs_to :city, optional: true
  belongs_to :tag, optional: true

  validates :user_id, presence: true
  validates :name, presence: true

  scope :suitable_by_city, ->(city_id) { where(arel_table[:city_id].eq(city_id).or(arel_table[:city_id].eq(nil)))  }
  scope :suitable_by_tag_ids, ->(tag_ids) { where(arel_table[:tag_id].in(tag_ids).or(arel_table[:tag_id].eq(nil)))  }

  scope :suitable_by_time, ->(event_beginning_time) {
    where(arel_table[:begin_interval].lt(event_beginning_time))
      .or(where(arel_table[:end_interval].gt(event_beginning_time)))
      .or(where(begin_interval: nil, end_interval: nil))
  }
end

app/models/filter_builder.rb
class FilterBuilder
  attr_reader :user, :filter_params

  def self.build_filter(user, filter_params)
    instance = new(user, filter_params)
    instance.build
  end

  def initialize(user, filter_params)
    @user = user
    @filter_params = filter_params
  end

  def build
    user.filters.build(normalized_params)
  end

  def normalized_params
    result = filter_params.select{ |k, v| v.present? }
    result[:name] ||= "Filter##{Time.now.to_f}"
    result
  end
end

app/models/place.rb
class Place < ApplicationRecord
  include IdentifiedSearch

  has_many :events
  belongs_to :city

  validates :city_id, presence: true
  validates :title, presence: true
  validates :description, presence: true

  def id_string
    "#{city.name} / #{title}"
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  has_one :event, through: :topic

  validates :message, presence: true
  validates :user_id, presence: true
  validates :topic_id, presence: true
end

app/models/post_creator.rb
class PostCreator
  attr_reader :user, :topic_id, :topic

  def initialize(user, topic_id)
    @user = user
    @topic_id = topic_id
    @topic = Topic.find(topic_id)
  end

  def create!(params)
    topic.posts.create!(params.merge(user_id: user.id))
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles


  belongs_to :resource,
             :polymorphic => true,
             :optional => true


  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/tag.rb
class Tag < ApplicationRecord
  include IdentifiedSearch

  has_and_belongs_to_many :events, join_table: 'events_tags'

  validates :name, presence: true

  def id_string
    name
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :event
  has_many :posts

  validates :title, presence: true
  validates :description, presence: true
  validates :event_id, presence: true

  delegate :title, to: :event, prefix: true
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :validatable#, :confirmable

  has_many :filters
  has_many :posts

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header_links.html.slim
- if current_user.has_role?(:admin)
  .admin-link.inline-block
    = link_to 'Admin panel', admin_root_path
.auth.inline-block
  = link_to 'Log out', destroy_user_session_path, method: :delete

app/views/layouts/_sign_in_form.html.slim
= form_for :user, url: user_session_path do |f|
  span
    = f.text_field :email, style: 'width: 200px', placeholder: 'e-mail', id: 'sign-in-user-email'
  span
    = f.text_field :password, type: 'password', style: 'width: 200px', placeholder: 'password', id: 'sign-in-user-password'
  span
    = f.submit 'log in'

app/views/layouts/_sign_up_form.html.slim
= form_for :user, url: users_path do |f|
  span
    = f.text_field :email, style: 'width: 200px', placeholder: 'e-mail', id: 'new-user-email'
  span
    = f.text_field :name, style: 'width: 200px', placeholder: 'name', id: 'new-user-name'
  span
    = f.text_field :password, type: 'password', style: 'width: 200px', placeholder: 'password', id: 'new-user-password'
  span
    = f.text_field :password_confirmation, type: 'password', style: 'width: 200px', placeholder: 'password confirmation', id: 'new-user-password-confirmation'
  span
    = f.submit 'Register'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type" /
    title NewsPortal
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
  body
    .header
      - if user_signed_in?
        = render partial: 'layouts/header_links'
      - else
        .sign-in.inline-block
          = render partial: 'layouts/sign_in_form'
        .sign-up.hidden
          = render partial: 'layouts/sign_up_form'

        = button_tag 'Sign in', class: 'hidden sign-in-switcher', data: { activate: 'sign-in' }
        = button_tag 'Sign up', class: 'inline sign-up-switcher', data: { activate: 'sign-up' }
    .main-block
      .sidebar
        = link_to 'Events', events_path
      .content
        = yield

    - if user_signed_in?
      .data-store (data-current-filter-ids=current_user.filters.ids)